routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('offers', 'OffersController');
    Route::resource('trades', 'TradesController');
    Route::post('offers/toggle', 'OffersController@toggle')->name('offers.disable');
    Route::post('trades/cancel', 'TradesController@cancel')->name('trades.cancel');
    Route::post('trades/accept', 'TradesController@accept')->name('trades.acept');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/TradesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\TradeCreateRequest;
use App\Http\Requests\TradeUpdateRequest;
use App\Repositories\TradeRepository;
use App\Validators\TradeValidator;

/**
 * Class TradesController.
 *
 * @package namespace App\Http\Controllers;
 */
class TradesController extends Controller
{
    /**
     * @var TradeRepository
     */
    protected $repository;

    /**
     * @var TradeValidator
     */
    protected $validator;

    /**
     * TradesController constructor.
     *
     * @param TradeRepository $repository
     * @param TradeValidator $validator
     */
    public function __construct(TradeRepository $repository, TradeValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $trades = $this->repository->paginate();

        if (request()->wantsJson()) {
            return response()->json([
                'data' => $trades,
            ]);
        }

        return view('trades.index', compact('Trades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  TradeCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function checkOffer(TradeCreateRequest $request)
    {
        return response()->json($this->validator->with($request->all())->pases(ValidatorInterface::RULE_CREATE));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  TradeCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(TradeCreateRequest $request)
    {
        try {
            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $trade = $this->repository->create($request->all());

            $response = [
                'message' => 'Trade created.',
                'data'    => $trade->toArray(),
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $trade = $this->repository->find($id);

        if (request()->wantsJson()) {
            return response()->json([
                'data' => $trade,
            ]);
        }

        return view('trades.show', compact('Trade'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $trade = $this->repository->find($id);

        return view('trades.edit', compact('Trade'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  TradeUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(TradeUpdateRequest $request, $id)
    {
        try {
            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $trade = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Trade updated.',
                'data'    => $trade->toArray(),
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {
            return response()->json([
                'message' => 'Trade deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Trade deleted.');
    }
}

resources/views/trades/create.blade.php
@extends('layouts.app')

@include('partials.content-edit-add-header')

@section('content')
    <div class="container-fluid">
        <div class="card card-primary">
            <div class="card-header display-4">Create Offer</div>
            <div class="card-body">
                {!! Form::open(['route' => 'offers.store', 'class' => 'form']) !!}

                    @include('offers.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/trades/edit.blade.php
@extends('layouts.app')

@include('partials.content-edit-add-header')

@section('content')
    <div class="page-content container-fluid browse">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($model, ['route' => ['offers.update', $model->id], 'method' => 'patch']) !!}

                        @include('offers.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
    </div>
@endsection

resources/views/trades/fields.blade.php
<!-- Currency Field -->
<div class="form-group col-sm-12">
    {!! Form::label('currency_id', 'Currency:') !!}
    {!! Form::select('currency_id', \App\Entities\Currency::limit(10)->pluck('currency', 'id'), null, [
        'class' => 'form-control select2',
        'onchange' => 'helpers.calculatePrice()'
    ]) !!}
</div>

<!-- Payment Method Field -->
<div class="form-group col-sm-12">
    {!! Form::label('payment_method_id', 'Payment Method:') !!}
    {!! Form::select('payment_method_id', \App\Entities\PaymentMethod::limit(10)->pluck('name', 'id'), null, [
        'class' => 'form-control select2'
    ]) !!}
</div>

<!-- Minimum Amount Field -->
<div class="form-group col-sm-12">
    {!! Form::label('amount_min', 'Min accepable amount:') !!}
    {!! Form::number('amount_min', null, [
        'class' => 'form-control',
        'onchange' => 'helpers.calculatePrice',
        'step' => '0.00000001',
        'placeholder' => "Minimum amount you'll accept"
    ]) !!}
</div>

<!-- Minimum Amount Field -->
<div class="form-group col-sm-12">
    {!! Form::label('amount_max', 'Max acceptable amount:') !!}
    {!! Form::number('amount_max', null, [
        'class' => 'form-control',
        'onchange' => 'helpers.calculatePrice()',
        'step' => '0.00000001',
        'placeholder' => "Maximum amount you'll accept"
    ]) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12">
    {!! Form::label('markup', 'Markup:') !!}
    <div class="input-group">
        <span class="input-group-text">percentage</span>
            {!! Form::number('markup', null, [
                'class' => 'form-control',
                'onchange' => 'helpers.calculatePrice()',
                'min' => 0,
                'placeholder' => 'Markup percentage: 0+'
            ]) !!}
    </div>
</div>

<div class="form-group col-sm-12">
    {!! Form::label('final_price', 'Final Price:') !!}
    <div class="input-group">
        <span id="final_price_currency" class="input-group-text"></span>
        {!! Form::text('final_price', null, ['class' => 'form-control', 'readonly' => true]) !!}
    </div>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('home') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/trades/index.blade.php
@extends('layouts.app')

@include('partials.content-index-header')

@section('content')
    <div class=" container-fluid browse">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                 @include('offers.table')
            </div>
        </div>
    </div>
@endsection

resources/views/trades/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Offer
        </h1>
    </section>
    <div class="page-content container-fluid browse">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('offers.show_fields')
                    <a href="{!! route('offers.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/trades/show_fields.blade.php
<ul class="list-group">
    <li class="list-group-item">
        ID
        <span class="badge badge-primary badge-pill">{{ $model->id }}</span>
    </li>
    <li class="list-group-item">
        Final Price
        <span class="badge badge-primary badge-pill">{{ $model->finalPrice }}</span>
    </li>
    <li class="list-group-item">
        Markup on Original
        <span class="badge badge-primary badge-pill">{{ $model->markup }}</span>
    </li>
    <li class="list-group-item">
        Currency
        <span class="badge badge-primary badge-pill">{{ $model->currency->code }}</span>
    </li>
    <li class="list-group-item">
        Payment Method
        <span class="badge badge-primary badge-pill">{{ $model->paymentMethod->name }}</span>
    </li>
    <li class="list-group-item">
        Min Acceptable Offer
        <span class="badge badge-primary badge-pill">{{ $model->amount_min }}</span>
    </li>
    <li class="list-group-item">
        Max Acceptable OFfer
        <span class="badge badge-primary badge-pill">{{ $model->amount_max }}</span>
    </li>
</ul>

resources/views/trades/table.blade.php
<table class="table table-responsive" id="offers-table">
    <thead>
        <th>By</th>
        <th>Payment Method</th>
        <th>Min</th>
        <th>Max</th>
        <th>BTC Price</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($models as $model)
        <tr>
            <td>{!! $model->user->name !!}</td>
            <td>{!! $model->paymentMethod->name !!}</td>
            <td>{!! $model->min !!}</td>
            <td>{!! $model->max !!}</td>
            <td>{!! $model->final_price !!}</td>
            <td>
                {!! Form::open(['route' => ['offers.destroy', $model->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('offers.show', [$model->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('offers.edit', [$model->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>