routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('offers', 'OffersController');
    Route::resource('trades', 'TradesController');
    Route::post('offers/toggle', 'OffersController@toggle')->name('offers.disable');
    Route::post('trades/cancel', 'TradesController@cancel')->name('trades.cancel');
    Route::post('trades/accept', 'TradesController@accept')->name('trades.acept');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/content-edit-add-header.blade.php
@section('header')
    <div class="row align-items-center justify-content-start">
        <div class="col-sm-2">
            <a href="{{ url()->previous() }}" class="btn">Back</a>
        </div>
        <div class="col-sm-10">
            <h1 class="justify-self-center text-center">
                {{title_case(str_replace('.', ' ', request()->route()->getName()))}}
            </h1>
        </div>
    </div>
@endsection;

resources/views/partials/content-index-header.blade.php
@section('header')
    <div class="row align-items-center justify-content-start">
        <div class="col-sm-2">
            <a href="{{ url()->previous() }}" class="btn">Back</a>
        </div>
        <div class="col-sm-10">
            <h1 class="justify-self-center text-center">
                {{title_case(str_replace('.', ' ', request()->route()->getName()))}}
            </h1>
        </div>
    </div>
@endsection;

resources/views/partials/offers.blade.php
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Owner</th>
            <th>Payment Method</th>
            <th>Min/Max</th>
            <th>BTC Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @forelse ($offers as $offer)
        <tr>
            <td>{{$offer->user->name}}</td>
            <td>{{$offer->paymentMethod->name}}</td>
            <td>{{$offer->amount_min}} / {{$offer->amount_max}}</td>
            <td>{{$offer->fomattedFinalPrice}}</td>
            <td class="col-sm-4">
                @if(auth()->check() && !auth()->user()->ownsOffer($offer))
                {!! Form::open(['route' => 'trades.store', 'class' => 'form']) !!}
                    <div class="form-group mb-0">
                        {!! Form::hidden('offer_id', $offer->id) !!}
                        {!! Form::number('fiat_amount', $offer->amount_min, [
                            'class' => 'form-control',
                            'step' => '0.00000001',
                            'placeholder' => "Your Offer",
                            'min' => $offer->amount_min,
                            'max' => $offer->amount_max,
                            'value' => $offer->amount_min
                        ]) !!}
                    </div>
                    <div class="form-group row mx-0">
                        <div class="input-group col-sm-12 mx-0 px-0">
                            <div class="input-group-prepend col-sm-6 px-0">
                                <span class="btn btn-info btn-block rounded-bottom">{{$offer->currency->code}}</span>
                            </div>
                            <div class="input-group-append col-sm-6 px-0">
                            <button id="buy{{$offer->id}}" type="submit" class="btn btn-block rounded-bottom" >Buy</button>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                @elseif(auth()->check() && auth()->user()->ownsOffer($offer))
                <div class="btn-group">
                    <a class="btn btn-info" href="{{route('offers.edit', ['id' => $offer->id])}}">Edit</a>
                    <form method="POST" onsubmit="return confirm('Are you sure?')" action="{{route('offers.destroy', ['id' => $offer->id])}}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                    <a class="btn {{$offer->is_active ? 'btn-disabled' : 'btn-info'}}" href="{{route('offers.disable', ['id' => $offer->id])}}">{{$offer->is_active ? 'Disable' : 'Enable'}}</a>
                </div>
                @endif
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="5">
                No offers!
                @if(!auth()->guest())
                    <a href="/offers/create" class="display-5">Create an offer</a>
                @endif
            </td>
        </tr>
        @endforelse
    </tbody>
</table>

resources/views/partials/trades.blade.php
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @forelse ($trades as $trade)
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        @empty
        <tr>
            <td colspan="5">
                No trades!
                @if(!auth()->guest())
                    <a href="/" class="display-5">Accept an available offer</a>
                @endif
            </td>
        </tr>
        @endforelse
    </tbody>
</table>